import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

def KDockRepoName = "LuckyPray/DexKit-Doc"

def libVersion = "2.0.7"

android {
    namespace = "org.luckypray.dexkit"
    compileSdk = 34
    ndkVersion = "26.1.10909125"

    defaultConfig {
        minSdk = 21
        targetSdk = 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static"
                def flags = [
                        "-funwind-tables",
                        "-fasynchronous-unwind-tables",
                        "-Qunused-arguments",
                        "-fno-rtti",
                        "-fno-exceptions",
                        "-fvisibility=hidden",
                        "-fvisibility-inlines-hidden",
                        "-Wno-unused-value",
                        "-Wno-unused-variable",
                        "-Wno-unused-command-line-argument",
                ]
                cppFlags = ["-std=c++20"] + flags
                cFlags = ["-std=c18"] + flags
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            externalNativeBuild {
                cmake {
                    def releaseFlags = [
                            "-ffunction-sections",
                            "-fdata-sections",
                            "-Wl,--gc-sections",
                            "-Wl,--exclude-libs,ALL",
                            "-Wl,--strip-all",
                            "-Wl,-z,max-page-size=16384",
                            "-flto=full",
                    ]
                    def configFlags = [
                            "-Oz",
                            "-DNDEBUG"
                    ].join(" ")
                    cppFlags += releaseFlags
                    cFlags += releaseFlags
                    arguments += [
                            "-DCMAKE_BUILD_TYPE=Release",
                            "-DCMAKE_CXX_FLAGS_RELEASE=$configFlags",
                            "-DCMAKE_C_FLAGS_RELEASE=$configFlags",
                    ]
                }
            }
            consumerProguardFiles "proguard-rules.pro"
        }

        debug {
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_CXX_FLAGS_DEBUG=-Og", "-DCMAKE_C_FLAGS_DEBUG=-Og"
                }
            }
        }

    }

    // 移除了手动设置 SrcDirs 的部分，改用标准的项目依赖
    // sourceSets {
    //     main {
    //         manifest.srcFile("AndroidManifest.xml")
    //         java.setSrcDirs(["${project(':dexkit').projectDir}/src/main/java"])
    //     }
    // }

    externalNativeBuild {
        cmake {
            path file("CMakeLists.txt")
            version "3.18.1"
        }
    }

//    buildFeatures {
//        prefab true
//    }
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    kotlinOptions.languageVersion = "1.7"
}

dependencies {
    api(project(":dexkit")) // 使用 api 确保 app 也能看到 dexkit 的源码
    api("androidx.recyclerview:recyclerview:1.2.1")
    implementation("com.google.flatbuffers:flatbuffers-java:23.5.26")
    // implementation("dev.rikka.ndk.thirdparty:cxx:1.2.0")
    //noinspection DifferentStdlibGradleVersion
    implementation("org.jetbrains.kotlin:kotlin-stdlib") {
        version {
            require "$kotlin_require_version"
        }
    }

    lintPublish(project(":lint-rules"))
}

// 移除了 mavenPublishing, dokkaHtml 和 updateKDoc 任务
