import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("java-library")
    id("org.jetbrains.kotlin.jvm")
}

// 移除了针对主机的 cmake 插件和配置

java {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    kotlinOptions.languageVersion = "1.7"
    kotlinOptions.freeCompilerArgs += [
            "-opt-in=kotlin.RequiresOptIn",
    ]
}

test {
    systemProperty("java.library.path", "${layout.buildDirectory.file("library").get().asFile.absolutePath}")
    systemProperty("apk.path", "${layout.projectDirectory.file("apk").asFile.absolutePath}")
}

dependencies {
    implementation("com.google.flatbuffers:flatbuffers-java:23.5.26")
    testImplementation("junit:junit:4.13.2")
}

afterEvaluate {
//    tasks.register("copyLibrary") {
//        def build = tasks.cmakeBuild
//        dependsOn(build)
//        doLast {
//            copy {
//                from layout.buildDirectory.file("cmake").get()
//                into layout.buildDirectory.file("library").get()
//                include("**/*.so", "**/*.dll", "**/*.dylib")
//                eachFile {
//                    path = name
//                }
//                includeEmptyDirs = false
//            }
//        }
//    }
//    tasks.jar.dependsOn(tasks.copyLibrary)

//    tasks.testClasses.dependsOn(tasks.copyLibrary)
}

//evaluationDependsOn(":demo")